resource_groups:
  main:
    name: ${rg_name}
    location: ${region}

vnets:
  main:
    created: true
    name: ${vnet_name}
    location: ${region}
    rg_name: ${vnet__rg_name}
    ip_ranges:
      - 10.0.0.0/16
    subnets:
      - name: network_appliances
        ip_ranges:
          - 10.0.0.0/24
      - name: workloads
        ip_ranges:
          - 10.0.64.0/18

application_gateways:
  main:
    created: true
    name: ${appgw_name}
    rg_name: ${appgw__rg_name}
    location: ${region}

    sku:
      name: Standard_v2
      tier: Standard_v2
      capacity: 1

    gateway_ip_configuration:
      vnet_name: TESTPROJECT-DEV-GENERAL-00
      subnet_name: network_appliances

    fe_ip_config:
      protocol: Http
      port: 80
    be_config:
      cookie_based_affinity: Disabled
      path: /path1/
      port: 80
      protocol: Http
      request_timeout: 60

    request_routing_rule:
      rule_type: Basic
      priority: 1

aks_clusters:
  main:
    created: true
    name: ${aks__name}
    location: ${region}
    rg_name: ${aks__rg_name}

    vnet_subnet_id: ${aks__vnet_subnet_id}
    dns_prefix: exampleaks1

    network_profile:
      network_plugin: azure
      network_plugin_mode: overlay
      pod_cidr: 10.0.128.0/18
      service_cidr: 10.0.192.0/18
      dns_service_ip: 10.0.192.10

    ingress_application_gateway:
      gateway_id: ${aks__ingress_appgw_id}
      vnet_id: ${aks__vnet_id}
      public_ip_ids:
        - /subscriptions/7c103106-7bc8-4282-906d-b6df27eb2c14/resourceGroups/TESTPROJECT-DEV-GENERAL-00/providers/Microsoft.Network/publicIPAddresses/TESTPROJECT-DEV-GENERAL-00

    k8s_version: 1.32.6

    default_node_pool:
      name: default
      node_count: 1
      vm_size: Standard_B2as_v2
    cluster_node_pool:
      - name: frontend
        node_count: 1
        vm_size: Standard_B2as_v2
      - name: backend
        node_count: 1
        vm_size: Standard_B2as_v2

    # workload_identity:
    #   enabled: true
    #   federated_identity:
    #     - name: aks-workload-identity
    #       namespace: jenkins
    #       service_account: jenkins
