# -- HashiCorp Vault Cluster ---
vault_dedicated_cluster_list:
  main:
    created: true
    hvn:
      enable_peering: false
      id: ${hvn_id}
      cidr_block: ""
      route_id: ${route_id}
      region: ${region}
      cloud_provider: aws
    cluster:
      id: ${cluster_id}
      peering_id: testproject-dev
      tier: dev
      public_endpoint: true

vault_component_list:
  main:
    vault_cluster:
      endpoint: ${vault_cluster__address}
      admin_token: ${vault_cluster__admin_token}

    k8s_cluster_info:
      name: ${k8s_cluster_name}
      region: ${region}
      platform: ${platform}
      resource_group: "" # Keep empty for EKS (AWS)

    vso:
      enabled: true
      repository: "https://helm.releases.hashicorp.com"
      chart: "vault-secrets-operator"
      namespace: "vault-secrets-operator"
      version: "1.0.1"

    # secret_from_url: https://terragrunt-input.s3.us-east-1.amazonaws.com/secrets.yaml
    secrets_from_s3:
      bucket: ${tf_input_bucket_name}
      key: secrets.yaml

    component:
      roles:
        - name: postgresql
          policies:
            - name: postgresql
              content: |
                path "*" {
                  capabilities = ["read"]
                }
          service_account: vault-postgresql
          namespace: postgresql

        - name: mongodb-sharded
          policies:
            - name: mongodb-sharded
              content: |
                path "*" {
                  capabilities = ["read"]
                }
          service_account: vault-mongodb-sharded
          namespace: mongodb-sharded

        - name: jenkins
          policies:
            - name: jenkins
              content: |
                path "*" {
                  capabilities = ["read"]
                }
          service_account: vault-jenkins
          namespace: jenkins

        - name: jenkins-inbound-agent
          policies:
            - name: jenkins-inbound-agent
              content: |
                path "*" {
                  capabilities = ["read"]
                }
          service_account: vault-jenkins-inbound-agent
          namespace: jenkins-inbound-agent

        - name: grafana-dashboard
          policies:
            - name: grafana-dashboard
              content: |
                path "*" {
                  capabilities = ["read"]
                }
          service_account: vault-grafana-dashboard
          namespace: grafana-dashboard
          
        - name: arc-runners
          policies:
            - name: arc-runners
              content: |
                path "*" {
                  capabilities = ["read"]
                }
          service_account: vault-arc-runners
          namespace: arc-runners