main:
  k8s_cluster:
    name: ${k8s_cluster_name}
    region: ${region}
    platform: ${platform}
    resource_group: ""

  alb_controller:
    enabled: true
    service_account_role_arn: "${service_account_role_arn}"
    vpc_id: "${vpc_id}"

  k8s_resources:
    git_repo:
      name: "ArgoCD-Apps"
      author: "khangtictoc"
      branch: "main"

    prerequisites:
      manifests:
        path_list:
          - "manifest/${platform}/default-storageclass.yaml"

      helm:
        bootstrap:
          enabled: true
          repository: "https://bootstrap-71b994.gitlab.io"
          chart: "bootstrap"
          namespace: "default"
          version: "0.2.0"

    post_install:
      path_list:
        - "manifest/oss/nginx/ingress-alb-to-nginx.yaml"
        - "manifest/oss/velero/schedule.yaml"

  # --- List of Platform Services ---------------------------

  apps:
    nginx:
      enabled: true
      repository: "oci://ghcr.io/nginx/charts"
      chart: "nginx-ingress"
      namespace: "nginx-ingress"
      version: "2.3.0"

    cert-manager:
      enabled: true
      repository: "oci://quay.io/jetstack/charts"
      chart: "cert-manager"
      namespace: "cert-manager"
      version: "v1.18.2"

    arc:
      enabled: true
      repository: "oci://ghcr.io/actions/actions-runner-controller-charts"
      chart: "gha-runner-scale-set-controller"
      namespace: "arc-systems"
      version: "0.14.2"

    arc-runners:
      enabled: true
      repository: "oci://ghcr.io/actions/actions-runner-controller-charts"
      chart: "gha-runner-scale-set"
      namespace: "arc-runners"
      version: "0.14.2"

    jenkins:
      enabled: true
      repository: "oci://ghcr.io/jenkinsci/helm-charts"
      chart: "jenkins"
      namespace: "jenkins"
      version: "5.8.124"

    jenkins-inbound-agent:
      enabled: true
      repository: "https://khangtictoc.github.io/jenkins-inbound-agent-helm-chart"
      chart: "jenkins-inbound-agent"
      namespace: "jenkins-inbound-agent"
      version: "0.17.0"

    postgresql:
      enabled: true
      repository: "oci://registry-1.docker.io/bitnamicharts"
      chart: "postgresql"
      namespace: "postgresql"
      version: "18.0.17"

    mongodb-sharded:
      enabled: true
      repository: "oci://registry-1.docker.io/bitnamicharts"
      chart: "mongodb-sharded"
      namespace: "mongodb-sharded"
      version: "9.3.6"

    grafana-loki:
      enabled: true
      repository: "https://grafana.github.io/helm-charts"
      chart: "loki"
      namespace: "grafana-loki"
      version: "6.46.0"

    grafana-mimir:
      enabled: true
      repository: "https://grafana.github.io/helm-charts"
      chart: "mimir-distributed"
      namespace: "grafana-mimir"
      version: "5.8.0"

    grafana-tempo:
      enabled: true
      repository: "https://grafana-community.github.io/helm-charts"
      chart: "tempo-distributed"
      namespace: "grafana-tempo"
      version: "2.3.2"

    grafana-alloy:
      enabled: true
      repository: "https://grafana.github.io/helm-charts"
      chart: "alloy"
      namespace: "grafana-alloy"
      version: "1.5.3"

    grafana-dashboard:
      enabled: true
      repository: "https://grafana-community.github.io/helm-charts/"
      chart: "grafana"
      namespace: "grafana-dashboard"
      version: "11.1.8"

    velero:
      enabled: true
      repository: "https://vmware-tanzu.github.io/helm-charts"
      chart: "velero"
      namespace: "velero"
      version: "11.1.1"

  app_values:
    grafana-loki:
      - name: 'serviceAccount.annotations.eks\.amazonaws\.com/role-arn'
        value: "${loki_role_arn}"

    velero:
      - name: "configuration.backupStorageLocation[0].bucket"
        value: "${velero_bucket_name}"

    aws-load-balancer-controller:
      - name: "clusterName"
        value: ${k8s_cluster_name}
      - name: serviceAccount.create
        value: "false"
      - name: serviceAccount.name
        value: "aws-load-balancer-controller"
      - name: region
        value: ${region}
      - name: vpcId
        value: ${vpc_id}
